import LessonLayout from '../../components/LessonLayout';
import CodeBlock from '../../components/CodeBlock';
import InfoBox from '../../components/InfoBox';
import InteractiveChallenge from '../../components/InteractiveChallenge';

export default function DddDomainEvents() {
  return (
    <LessonLayout
      title="Domain Events & the Repository Pattern"
      sectionId="ddd"
      lessonIndex={3}
      prev={{ path: '/ddd/tactical', label: 'Tactical DDD: Entities, Value Objects & Aggregates' }}
      next={{ path: '/ddd/event-storming', label: 'Event Storming: Discovering Bounded Contexts' }}
    >
      <p>
        The previous lesson built <code>Order</code> as an Aggregate Root whose{' '}
        <code>addLine()</code> method enforces invariants on every mutation. Two questions follow
        naturally from that: when something significant happens to the aggregate, how does the rest of
        the system find out? And how does that aggregate get loaded and saved without every caller
        needing to know it is secretly backed by a database? Those are Domain Events and the Repository
        pattern — the last two tactical building blocks.
      </p>

      <h2>Domain Events: Facts, Not Requests</h2>

      <p>
        A <strong>Domain Event</strong> is a record that something happened inside the domain that other
        code might care about — <code>OrderPlaced</code>, <code>OrderCancelled</code>. Three properties
        matter: it is <strong>immutable</strong> (a fact about the past does not change), it is{' '}
        <strong>named in the past tense</strong> (an order was placed — the event is not asking anyone to
        place one), and it carries <strong>whatever data a handler needs to react</strong>, so the handler
        does not have to turn around and re-fetch the aggregate just to find out what changed.
      </p>

      <InfoBox variant="note" title="This Is the Same Concept as the Microservices Section — Different Scope">
        <p>
          The Microservices section&apos;s Event-Driven Architecture lesson covers events flowing{' '}
          <strong>between</strong> services over a broker — that lesson's infrastructure (topics,
          consumers, delivery guarantees) is not being re-taught here. A Domain Event is the same idea at
          a smaller starting scope: it can be born and handled entirely <strong>inside one aggregate or
          one service</strong>, in-process, with nothing external involved. Whether that event ever gets
          published across a service boundary is a separate decision, made later — everything below
          happens without a message broker in sight.
        </p>
      </InfoBox>

      <p>
        Here is the event itself — a Java <code>record</code> is a natural fit, since records are
        transparent, immutable data carriers by construction:
      </p>

      <CodeBlock language="java" title="OrderPlaced.java — a Domain Event">
{`import java.time.Instant;

/** Immutable, past tense, carries exactly what a handler needs to react. */
public record OrderPlaced(OrderId orderId, long totalCents, Instant placedAt) {
}`}
      </CodeBlock>

      <p>
        <code>OrderId</code> here is another small record — <code>public record OrderId(String value) {'{}'}</code> —
        a typed wrapper instead of a bare <code>String</code>, so an <code>OrderId</code> can never be
        accidentally passed where a <code>CustomerId</code> was expected. It is itself a Value Object from
        the previous lesson, just auto-generated by <code>record</code> instead of hand-written.
      </p>

      <p>
        The aggregate records the event as a side effect of the method that changes its state, rather
        than some unrelated piece of code guessing after the fact that a status change &quot;probably
        means&quot; an order was placed:
      </p>

      <CodeBlock language="java" title="Order.java — records an event when it changes state">
{`import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

public final class Order {
    private final OrderId id;
    private OrderStatus status;
    private final List<OrderLine> lines = new ArrayList<>();
    private final List<Object> domainEvents = new ArrayList<>();

    public Order(OrderId id, OrderStatus status) {
        this.id = id;
        this.status = status;
    }

    public OrderId getId() { return id; }
    public long totalCents() { return lines.stream().mapToLong(OrderLine::lineTotalCents).sum(); }

    public void addLine(String product, int quantity, long unitPriceCents) {
        if (status != OrderStatus.OPEN) {
            throw new IllegalStateException("Cannot add a line to order " + id.value() + " in status " + status);
        }
        lines.add(new OrderLine(product, quantity, unitPriceCents));
    }

    /** State-changing method: transitions status AND records the fact that it happened. */
    public void place() {
        if (status != OrderStatus.OPEN) {
            throw new IllegalStateException("Cannot place order " + id.value() + " — it is " + status);
        }
        this.status = OrderStatus.PLACED;
        domainEvents.add(new OrderPlaced(id, totalCents(), Instant.now()));
    }

    /** Returns events recorded since the last pull, then clears them — each event delivered once. */
    public List<Object> pullDomainEvents() {
        List<Object> copy = new ArrayList<>(domainEvents);
        domainEvents.clear();
        return copy;
    }
}`}
      </CodeBlock>

      <p>
        A handler still needs somewhere to register interest in a given event type, and something to
        invoke it when that type shows up. In production this job usually belongs to a framework — Spring
        has <code>ApplicationEventPublisher</code>, Axon and similar frameworks have a full event bus —
        but the mechanism underneath all of them is small enough to write from scratch, which is the
        clearest way to see what it actually does:
      </p>

      <CodeBlock language="java" title="DomainEventDispatcher.java — a minimal in-process dispatcher">
{`import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

public class DomainEventDispatcher {
    private final Map<Class<?>, List<Consumer<Object>>> handlers = new HashMap<>();

    public <T> void register(Class<T> eventType, Consumer<T> handler) {
        handlers.computeIfAbsent(eventType, k -> new ArrayList<>())
                .add(event -> handler.accept(eventType.cast(event)));
    }

    public void dispatch(Object event) {
        List<Consumer<Object>> registered = handlers.get(event.getClass());
        if (registered == null) return;
        for (Consumer<Object> handler : registered) {
            handler.accept(event);
        }
    }
}`}
      </CodeBlock>

      <p>
        Now the full chain, start to finish: build an order, place it, pull the recorded event, dispatch
        it, and confirm the handler actually ran with the right data. Compiled and run — real output in
        the comments:
      </p>

      <CodeBlock language="java" title="DomainEventDemo.java — Compiled and Run (real output in comments)">
{`public class DomainEventDemo {
    public static void main(String[] args) {
        DomainEventDispatcher dispatcher = new DomainEventDispatcher();
        List<String> confirmationLog = new ArrayList<>();

        dispatcher.register(OrderPlaced.class, event -> {
            confirmationLog.add("Sending confirmation email for order " + event.orderId().value()
                    + ", total " + event.totalCents() + "c");
        });

        Order order = new Order(new OrderId("order-500"), OrderStatus.OPEN);
        order.addLine("Desk Lamp", 1, 3500);
        order.addLine("Notebook", 3, 500);

        order.place();

        List<Object> events = order.pullDomainEvents();
        System.out.println("Events recorded by place(): " + events.size());
        // Events recorded by place(): 1

        for (Object event : events) {
            dispatcher.dispatch(event);
        }

        confirmationLog.forEach(System.out::println);
        // Sending confirmation email for order order-500, total 5000c

        System.out.println("Second pullDomainEvents() call returns: " + order.pullDomainEvents().size());
        // Second pullDomainEvents() call returns: 0

        OrderPlaced placed = (OrderPlaced) events.get(0);
        if (!placed.orderId().equals(order.getId()) || placed.totalCents() != order.totalCents()) {
            throw new AssertionError("event data did not match the aggregate");
        }
        System.out.println("ASSERTIONS PASSED: handler fired with the exact orderId and total from the aggregate.");
        // ASSERTIONS PASSED: handler fired with the exact orderId and total from the aggregate.
    }
}`}
      </CodeBlock>

      <p>
        Nothing about the confirmation-email logic lives inside <code>Order</code>. <code>place()</code>{' '}
        only records the fact that placing happened; the dispatcher is what decided a{' '}
        <code>String</code> got appended to <code>confirmationLog</code>. Add a second{' '}
        <code>register()</code> call for the same event type — say, one that reserves inventory — and{' '}
        <code>Order</code> does not change at all. That decoupling is the entire point.
      </p>

      <h2>The Repository Pattern, DDD-Flavored</h2>

      <p>
        &quot;Repository&quot; gets used loosely enough that it is worth being precise about the DDD
        version specifically. A DDD Repository is not a synonym for DAO, and it is not &quot;whatever
        class has the SQL in it.&quot; It gives calling code the illusion of an{' '}
        <strong>in-memory collection of Aggregate Roots</strong>: <code>save()</code> puts one in,{' '}
        <code>findById()</code> gets one out, and everything about how that actually happens — a JDBC
        connection, a JPA <code>EntityManager</code>, rows across three joined tables — stays completely
        invisible on the other side of the interface.
      </p>

      <p>
        The part that is easy to miss: a Repository&apos;s vocabulary is restricted to whole Aggregate
        Roots. It never hands out or accepts an individual child entity, because doing so would let
        calling code reach a child directly and mutate it without going through the root that is supposed
        to enforce invariants on it — exactly the boundary the previous lesson&apos;s{' '}
        <code>addLine()</code> exists to protect.
      </p>

      <CodeBlock language="java" title="OrderRepository.java — an interface restricted to the Aggregate Root">
{`import java.util.Optional;

public interface OrderRepository {
    void save(Order order);
    Optional<Order> findById(OrderId id);
}`}
      </CodeBlock>

      <p>
        A real implementation would wrap a database. For the demo, an in-memory <code>Map</code> plays
        that role — the point is the shape of the interface, not the storage engine behind it:
      </p>

      <CodeBlock language="java" title="InMemoryOrderRepository.java">
{`import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

public class InMemoryOrderRepository implements OrderRepository {
    private final Map<OrderId, Order> store = new HashMap<>();

    @Override
    public void save(Order order) {
        store.put(order.getId(), order);
    }

    @Override
    public Optional<Order> findById(OrderId id) {
        return Optional.ofNullable(store.get(id));
    }
}`}
      </CodeBlock>

      <CodeBlock language="java" title="RepositoryDemo.java — Compiled and Run (real output in comments)">
{`OrderRepository repository = new InMemoryOrderRepository();

Order order = new Order(new OrderId("order-77"), OrderStatus.OPEN);
order.addLine("Chair", 1, 12000);
repository.save(order);

// A freshly constructed OrderId with the same value — proving lookup works by
// VALUE equality (OrderId is a record / Value Object), not by object reference.
Optional<Order> found = repository.findById(new OrderId("order-77"));

System.out.println(found.isPresent());          // true
System.out.println(found.get().equals(order));  // true

Optional<Order> missing = repository.findById(new OrderId("does-not-exist"));
System.out.println(missing.isPresent());         // false`}
      </CodeBlock>

      <p>
        <code>found.get().equals(order)</code> is <code>true</code> for the same reason the previous
        lesson&apos;s <code>Order.equals()</code> compares only <code>id</code>: the repository is not
        guaranteed to hand back the exact same object reference it was given (a real implementation
        reconstructs the aggregate from rows every time), so equality has to be identity-based to mean
        anything.
      </p>

      <InfoBox variant="danger" title="What This Repository Deliberately Does NOT Have">
        <p>
          There is no <code>findOrderLineById(String lineId)</code> on{' '}
          <code>OrderRepository</code>, and there should never be one. <code>OrderLine</code> is a child
          entity — it is only supposed to be reachable by first loading its <code>Order</code> and going
          through the root, the same way <code>addLine()</code> is the only way to add one. A repository
          method that fetches a child directly hands out a reference the aggregate root never got a
          chance to protect: nothing stops that <code>OrderLine</code> from being mutated and saved back
          in a way that leaves the parent <code>Order</code>&apos;s invariants — its total, its status
          rules — silently violated. If code needs to work with a line item, the Repository still only
          gives out <code>Order</code>; reaching the line from there is <code>Order</code>&apos;s job, not
          the Repository&apos;s.
        </p>
      </InfoBox>

      <InteractiveChallenge
        question={"Your team's OrderRepository currently exposes only save(Order) and findById(OrderId). A teammate proposes adding List<OrderLine> findLinesByProduct(String product) directly to the repository, to avoid loading a whole Order just to inspect its lines. What's the problem with this, in DDD terms?"}
        options={[
          "Nothing — it's a reasonable performance optimization and repositories can expose whatever queries are convenient",
          "It bypasses the aggregate boundary: OrderLine is a child entity that should only be reached through its Order root, and a Repository should only load or save whole Aggregate Roots",
          "It's fine as long as OrderLine gets its own equals() and hashCode() methods",
          "It's only a problem if OrderLine objects are mutable"
        ]}
        correctIndex={1}
        explanation={"A DDD Repository's vocabulary is restricted to Aggregate Roots — that's what makes it give the illusion of an in-memory collection of Orders rather than a generic query API. Handing out a bare OrderLine lets callers mutate or persist it without ever going through Order.addLine(), which is exactly where invariants like 'no lines on a cancelled order' get enforced. Needing to look something up by product is a real requirement, but the fix is a method that still returns Order (or a read-only projection built for that one query), not one that leaks a child entity out of its aggregate."}
      />
    </LessonLayout>
  );
}
