import CodeBlock from '../../components/CodeBlock';
import InfoBox from '../../components/InfoBox';
import InteractiveChallenge from '../../components/InteractiveChallenge';
import LessonLayout from '../../components/LessonLayout';

function TsqlModifyingData() {
  return (
    <LessonLayout
      title="Modifying Data — OUTPUT, MERGE, Upserts"
      sectionId="tsql"
      lessonIndex={4}
      prev={{ path: '/tsql/aggregation', label: 'Aggregation & Window Functions' }}
      next={{ path: '/tsql/programmability', label: 'Stored Procedures, Functions & Error Handling' }}
    >
      <p>
        <code>INSERT</code>, <code>UPDATE</code> and <code>DELETE</code> are standard. What is worth
        your attention here is the <code>OUTPUT</code> clause, which is genuinely excellent and has no
        Postgres equivalent beyond <code>RETURNING</code>, and <code>MERGE</code>, which is famous and
        which you should mostly not use.
      </p>

      <h2>UPDATE ... FROM — A T-SQL Extension</h2>

      <CodeBlock language="sql" title="Updating one table from another">
{`UPDATE e
SET    e.salary = s.new_salary
FROM   emp AS e
JOIN   salary_import AS s ON s.emp_id = e.id
WHERE  s.batch_id = @batch;`}
      </CodeBlock>

      <InfoBox variant="danger" title="If the join matches multiple rows, you get a silent arbitrary winner">
        <p>
          Standard SQL would raise an error. T-SQL does not: if{' '}
          <code>salary_import</code> has two rows for the same <code>emp_id</code>, the{' '}
          <code>UPDATE</code> succeeds and one of them wins — <strong>non-deterministically</strong>,
          with no warning, and <code>@@ROWCOUNT</code> reports the employee updated once. You cannot
          tell from the result that the data was ambiguous.
        </p>
        <p style={{ marginTop: '0.5rem' }}>
          Before trusting an <code>UPDATE ... FROM</code>, verify the source is unique on the join
          key:
        </p>
        <CodeBlock language="sql" title="Check first">
{`SELECT emp_id, COUNT(*) FROM salary_import
WHERE batch_id = @batch GROUP BY emp_id HAVING COUNT(*) > 1;`}
        </CodeBlock>
      </InfoBox>

      <h2>The OUTPUT Clause</h2>

      <p>
        <code>OUTPUT</code> gives you access to the <code>inserted</code> and <code>deleted</code>{' '}
        pseudo-tables — the same ones triggers see — directly in a DML statement. An{' '}
        <code>UPDATE</code> can hand you the before <em>and</em> after values in one round trip:
      </p>

      <CodeBlock language="sql" title="Before and after, atomically">
{`UPDATE emp
SET    salary = salary + 1
OUTPUT deleted.id,
       deleted.salary  AS old_sal,
       inserted.salary AS new_sal
WHERE  id = 3;`}
      </CodeBlock>

      <CodeBlock language="text" title="Real output — SQL Server 2019">
{`id | old_sal | new_sal
---|---------|--------
 3 | 80      | 81`}
      </CodeBlock>

      <CodeBlock language="text" title="Which pseudo-table exists when">
{`INSERT   inserted only
UPDATE   both — deleted = before, inserted = after
DELETE   deleted only

OUTPUT ... INTO @table_variable   capture instead of returning
OUTPUT without INTO               returns a result set to the client`}
      </CodeBlock>

      <InfoBox variant="tip" title="The pattern this unlocks: claim rows atomically">
        <p>
          A work-queue dequeue that is safe under concurrency, in a single statement — no transaction
          block, no race between selecting and marking:
        </p>
        <CodeBlock language="sql" title="Atomic claim">
{`UPDATE TOP (10) job_queue
SET    status = 'processing', claimed_by = @worker
OUTPUT inserted.id, inserted.payload
WHERE  status = 'pending';`}
        </CodeBlock>
        <p style={{ marginTop: '0.5rem' }}>
          Because the update and the read are one statement, two workers cannot claim the same row.
          Doing this as <code>SELECT</code> then <code>UPDATE</code> requires an explicit transaction
          and a locking hint to be equally safe.
        </p>
      </InfoBox>

      <h2>Identity Columns</h2>

      <CodeBlock language="sql" title="Getting the generated key back">
{`CREATE TABLE t1 (id INT IDENTITY(1,1) PRIMARY KEY, v INT);

INSERT INTO t1(v) VALUES (9);

SELECT SCOPE_IDENTITY();   -- CORRECT: last identity in THIS scope
SELECT @@IDENTITY;         -- WRONG-ish: last identity in this SESSION,
                           -- including one generated by a TRIGGER
SELECT IDENT_CURRENT('t1');-- last identity for that TABLE, any session`}
      </CodeBlock>

      <InfoBox variant="warning" title="@@IDENTITY is a classic production bug">
        <p>
          If a trigger on <code>t1</code> inserts an audit row into another table with its own
          identity column, <code>@@IDENTITY</code> returns the <em>audit</em> row&apos;s id. Your code
          then associates child records with the wrong parent. The bug appears the day someone adds a
          trigger, in code that was written years earlier and never touched.
        </p>
        <p style={{ marginTop: '0.5rem' }}>
          Use <code>SCOPE_IDENTITY()</code>, or better, use <code>OUTPUT inserted.id</code>, which is
          unambiguous and works for multi-row inserts where the identity functions only give you one
          value.
        </p>
      </InfoBox>

      <h2>MERGE — Read This Before Using It</h2>

      <CodeBlock language="sql" title="The shape">
{`MERGE INTO target AS t
USING source AS s ON t.id = s.id
WHEN MATCHED THEN UPDATE SET t.val = s.val
WHEN NOT MATCHED BY TARGET THEN INSERT (id, val) VALUES (s.id, s.val)
WHEN NOT MATCHED BY SOURCE THEN DELETE;`}
      </CodeBlock>

      <p>
        It reads beautifully and it does upsert, insert and delete in one statement. It also has a
        long, well-documented history of bugs and concurrency hazards, and experienced SQL Server
        practitioners broadly advise against it in new code.
      </p>

      <CodeBlock language="text" title="The concrete objections">
{`- Under concurrency MERGE can deadlock or raise a duplicate-key error
  unless the target is locked with HOLDLOCK. The correct form is
  USING ... ON ... with the target hinted WITH (HOLDLOCK), and almost
  no example on the internet includes it.

- "WHEN NOT MATCHED BY SOURCE THEN DELETE" applies to the ENTIRE target
  table, not just the rows related to your source. A filter you forgot
  means you delete everything not in this batch.

- If the source produces duplicate keys, MERGE raises an error rather
  than picking arbitrarily (unlike UPDATE...FROM). That is BETTER, but
  it surprises people migrating from UPDATE...FROM.

- Multiple long-standing correctness bugs have been reported against it
  over the years. Many teams simply ban it.`}
      </CodeBlock>

      <CodeBlock language="sql" title="The boring alternative that behaves predictably">
{`BEGIN TRAN;

UPDATE t
SET    t.val = s.val
FROM   target AS t
JOIN   source AS s ON s.id = t.id;

INSERT INTO target (id, val)
SELECT s.id, s.val
FROM   source AS s
WHERE  NOT EXISTS (SELECT 1 FROM target t WHERE t.id = s.id);

COMMIT;`}
      </CodeBlock>

      <p>
        Two statements in a transaction. More typing, no surprises, and every developer on the team
        can read it. If you need it to be safe against concurrent writers, that is what the isolation
        lesson is for.
      </p>

      <h2>Deleting Efficiently</h2>

      <CodeBlock language="text" title="DELETE vs TRUNCATE">
{`DELETE FROM t;        logs every row, fires triggers, can be filtered,
                      keeps the identity seed
TRUNCATE TABLE t;     minimal logging, no triggers, no WHERE clause,
                      RESETS the identity seed to the start,
                      blocked if the table is referenced by a foreign key

Both are transactional — TRUNCATE can be rolled back. That surprises
people coming from MySQL, where it cannot.

For large deletes, delete in batches so the log and the locks stay small:
  WHILE 1 = 1
  BEGIN
      DELETE TOP (5000) FROM t WHERE created < @cutoff;
      IF @@ROWCOUNT = 0 BREAK;
  END`}
      </CodeBlock>

      <InteractiveChallenge
        question="Code inserts an order with INSERT then reads @@IDENTITY to get the new order id. It worked for years, then began attaching order lines to the wrong order — right after an audit trigger was added to the orders table. What is the cause?"
        options={[
          'The audit trigger is rolling back the original insert',
          '@@IDENTITY returns the last identity generated anywhere in the session, so it now returns the audit table\'s id rather than the order id — SCOPE_IDENTITY() or OUTPUT inserted.id is correct',
          'The identity seed on orders needs reseeding',
          'The trigger changed the isolation level',
        ]}
        correctIndex={1}
        explanation={"@@IDENTITY is session-scoped, not statement-scoped. A trigger that inserts into another table with an identity column runs inside the same session, so the last identity value generated is the audit row's, and that is what @@IDENTITY hands back. SCOPE_IDENTITY() is limited to the current scope and so ignores values created inside the trigger. The reason this is such a nasty bug is the delay between cause and effect: the insert code is correct-looking, untouched, and possibly years old, while the change that broke it happened in a completely different object. OUTPUT inserted.id avoids the whole class of problem and is the only one of the three that works for multi-row inserts."}
      />
    </LessonLayout>
  );
}

export default TsqlModifyingData;
